// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA2RpZecZl4RWonaEejB-56WxHNqynye8Q',
    appId: '1:185926144423:web:8a90b8b2945c1ddb166682',
    messagingSenderId: '185926144423',
    projectId: 'wallpaperappp-d6d3f',
    authDomain: 'wallpaperappp-d6d3f.firebaseapp.com',
    storageBucket: 'wallpaperappp-d6d3f.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCRVTqwPgKtUyBCq2hOZDj-ACxHUcZUuyE',
    appId: '1:185926144423:android:6e4771a3be9c789a166682',
    messagingSenderId: '185926144423',
    projectId: 'wallpaperappp-d6d3f',
    storageBucket: 'wallpaperappp-d6d3f.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA2Vvt-o0Q5gfROp0lks1nuxqH_tkFRdzA',
    appId: '1:185926144423:ios:998e2733b677dedc166682',
    messagingSenderId: '185926144423',
    projectId: 'wallpaperappp-d6d3f',
    storageBucket: 'wallpaperappp-d6d3f.firebasestorage.app',
    iosBundleId: 'com.example.helloWorld',
  );
}
